# wengwengweng

[package]
name = "glslview"
version = "0.0.0"
authors = ["tga <tga@enemyspy.xyz>"]
repository = "https://git.sr.ht/~slmjkdbtl/glslview"
edition = "2018"

[dependencies]
dirty = { path = "../DIRTY" }

